from turtle import *
Screen().setup(600, 600)
speed(0)
pensize(3)
circle(radius=100, steps=8)
up()
lt(90)
fd(10)
rt(90)
fillcolor('red')
begin_fill()
circle(radius=90, steps=8)
end_fill()
lt(90)
fd(60)
color('white')
write('STOP', align='center', font=('Times New Roman', 40, 'bold'))
